### ISSUE TITLE
Explain these lines?

### ISSUE THREAD

**Issue by djarbz** [lorenzo95/nftables-zbf#1]
Hello,

I am using your template as inspiration for my own ZBF and I don't quite understand these 2 lines, hoping you can provide some insight?
`fib daddr . iif type != { local, broadcast, multicast } counter drop`
`fib saddr . oif type != { local, broadcast, multicast } counter drop`

**Comment by lorenzo95** [comment]
Hello!

That's a great question. I found those lines on a blog back then somewhere. i don't remember where. They do solve an important issue that can easily be overlooked. Here is what it does: 

Lets say your router has two interfaces. Let them be 1.1.1.1/24 and the other one 1.1.10.1/24. You enabled ip_forward and you configured nftables to drop all forwarded packets. 

Now let's say you have a computer configured as 1.1.1.2/24 with a default gateway of 1.1.1.1. From that computer try to ping 1.1.10.1...it will respond. Basically, you can ping an internal interface on your router even so forwarding is blocked by the firewall. It turns out that the packet isn't forwarded at all but processed directly by the incoming interface to the kernel even so we thing it is being forwarded through the router. 

I guess in my head it translates to: If a packet comes in on an interface and the destination address is not the address of the interface that the packet came in on, drop it. Unless it is the ip of that incoming interface, broadcast or multicast the pass it. 

The two lines are therefore in place for security. Otherwise, someone could enumerate interfaces in your router that they should not be seeing. It's important to allow loopback connections as part of the config or some services can't connect to themselves anymore.

**Comment by djarbz** [comment]
Excellent explanation, thank you!
